### ISSUE TITLE
Please make it work on android

### ISSUE THREAD

**Issue by Rizen111** [ADIBzTER/borang#1]
Please make it work on android, i need this extension so much, nice project BTW love it.

**Comment by adibzter** [comment]
I'm afraid I can't make it work for Android. It seems complicated. It's better for you to use this [chrome extension](https://chrome.google.com/webstore/detail/borang/mokcmggiibmlpblkcdnblmajnplennol) instead of the website.

**Comment by Rizen111** [comment]
Im using kiwi browser support extension but didn't work

Pada tanggal Jum, 26 Nov 2021 21.13, Adib Zaini ***@***.***>
menulis:

**Comment by adibzter** [comment]
Hey @Rizen111 , Borang now works on mobile through browser either firefox or chrome on Android. Feel free to go to https://borang.skrin.xyz for more info
