### ISSUE TITLE
error: cannot post data

### ISSUE THREAD

**Issue by Lootbite** [ADIBzTER/borang#5]
it worked for me at the first time but after i left my computer for about 10 minutes , the message 'Error: Cannot post data appeared. I am not sure if it is my problem or the extensions problem. Pls give me an answer because I nd to use this for a presentation 2 days later. Thanks

**Comment by Iqmalhakim** [comment]
i have the same issues its not working with me

**Comment by adibzter** [comment]
Hey @Lootbite @Iqmalhakim , is this issue still valid?
